# Generated by Django 5.0.1 on 2024-01-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_subject_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentMarks',
            new_name='SubjectMarks',
        ),
    ]
