# Generated by Django 5.0.1 on 2024-01-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0010_receipe_slug_student_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
